[package]
name = "jwtck"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
base64 = "0.13.1"
chrono = "0.4.31"
colored_json = "3.0.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
